import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import '@mantine/core/styles.css';

import MasterLayout from "./layout/MasterLayout";
import { MantineProvider } from "@mantine/core";
import { theme } from "./theme";


export const metadata: Metadata = {
  title: "ThreadUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <MasterLayout>{children}</MasterLayout>
        </MantineProvider>
      </body>
    </html>
  );
}
