import { ICasualOutfit } from "../types/index.type";
import deminJacket from '../assets/casual/denim.jpeg'
import cottonTShirt from '../assets/casual/cotton-tshirt.jpeg'
import hoddie from '../assets/casual/hoddie.jpeg'
import overSizeTShirt from '../assets/casual/oversize-t-shirt.jpeg'
import pant from '../assets/casual/pant.jpg'
import shirt from '../assets/casual/shirt.jpg'
import slimFitChinos from '../assets/casual/slim-fit-chinos.jpeg'
import sneakers from '../assets/casual/sneakers.jpeg'
import poloTShirt from '../assets/casual/polo-t-shirt.jpg'

export const casualOutfits: ICasualOutfit[] = [
  {
    id: "8f9b2d12-71e3-4c72-84f1-5e3c1b1c9a01",
    title: "Classic Denim Jacket",
    description: "Timeless blue denim jacket with a relaxed fit and vintage wash.",
    price: 2499,
    trending: true,
    discount: true,
    originalPrice: 3499,
    discountedPrice: 2499,
    offerPercent: 29,
    image: deminJacket,
    variants: [
      { size: "S", price: 2399 },
      { size: "M", price: 2499 },
      { size: "L", price: 2599 },
      { size: "XL", price: 2699 },
    ],
  },
  {
    id: "9a2e6f94-64df-48f8-b42e-91cc1dc93802",
    title: "Cotton Graphic T-Shirt",
    description: "Soft cotton tee featuring a modern graphic print for casual looks.",
    price: 999,
    trending: false,
    discount: true,
    originalPrice: 1299,
    discountedPrice: 999,
    offerPercent: 23,
    image: cottonTShirt,
    variants: [
      { size: "S", price: 899 },
      { size: "M", price: 999 },
      { size: "L", price: 1099 },
      { size: "XL", price: 1199 },
    ],
  },
  {
    id: "a4f25cb2-61f4-4c9b-9bbd-0d4172037e03",
    title: "Slim Fit Chinos",
    description: "Comfortable cotton chinos perfect for office or weekend wear.",
    price: 1799,
    trending: true,
    discount: false,
    originalPrice: 1799,
    discountedPrice: 1599,
    offerPercent: 0,
    image: slimFitChinos,
    variants: [
      { size: "30", price: 1599 },
      { size: "32", price: 1599 },
      { size: "34", price: 1799 },
      { size: "36", price: 1799 },
    ],
  },
  {
    id: "c0e2d3a9-9041-4a7c-bb3d-8a5fbd20a304",
    title: "Linen Casual Shirt",
    description: "Lightweight linen shirt ideal for summer evenings.",
    price: 2199,
    trending: true,
    discount: true,
    originalPrice: 2799,
    discountedPrice: 2199,
    offerPercent: 21,
    image: shirt,
    variants: [
      { size: "S", price: 2099 },
      { size: "M", price: 2199 },
      { size: "L", price: 2299 },
      { size: "XL", price: 2399 },
    ],
  },
  {
    id: "f5b6a7e1-6e44-46c7-b7df-732cf24c0305",
    title: "Casual Hoodie",
    description: "Soft fleece hoodie designed for all-day comfort.",
    price: 1999,
    trending: false,
    discount: true,
    originalPrice: 2499,
    discountedPrice: 1999,
    offerPercent: 20,
    image: hoddie,
    variants: [
      { size: "S", price: 1899 },
      { size: "M", price: 1999 },
      { size: "L", price: 2099 },
      { size: "XL", price: 2199 },
    ],
  },
  {
    id: "1e5df0d9-12a3-4b94-bd41-7e12b4145a06",
    title: "Relaxed Fit Jeans",
    description: "Everyday jeans with a relaxed fit and durable stretch fabric.",
    price: 2599,
    trending: true,
    discount: false,
    originalPrice: 2599,
    discountedPrice: 2599,
    offerPercent: 0,
    image: pant,
    variants: [
      { size: "30", price: 2599 },
      { size: "32", price: 2599 },
      { size: "34", price: 2599 },
      { size: "36", price: 2599 },
    ],
  },
  {
    id: "9cc7d2e2-7a7d-4b42-9b9d-4cf52c36a108",
    title: "Striped Polo T-Shirt",
    description: "Classic striped polo tee with a modern slim fit.",
    price: 1499,
    trending: true,
    discount: false,
    originalPrice: 1499,
    discountedPrice: 1499,
    offerPercent: 0,
    image: poloTShirt,
    variants: [
      { size: "S", price: 1499 },
      { size: "M", price: 1499 },
      { size: "L", price: 1499 },
      { size: "XL", price: 1499 },
    ],
  },
  {
    id: "0d7a6f34-b96e-4b2b-bb64-42f7dfd9c910",
    title: "Oversized Sweatshirt",
    description: "Cozy oversized sweatshirt made with premium cotton blend.",
    price: 2299,
    trending: false,
    discount: true,
    originalPrice: 2899,
    discountedPrice: 2299,
    offerPercent: 21,
    image: overSizeTShirt,
    variants: [
      { size: "S", price: 2199 },
      { size: "M", price: 2299 },
      { size: "L", price: 2399 },
      { size: "XL", price: 2499 },
    ],
  },
  {
    id: "7b4f52b6-815d-4f8a-a20a-3fd7ab760909",
    title: "Casual Sneakers",
    description: "Lightweight sneakers for a relaxed and sporty everyday vibe.",
    price: 2799,
    trending: true,
    discount: true,
    originalPrice: 3499,
    discountedPrice: 2799,
    offerPercent: 20,
    image: sneakers,
    variants: [
      { size: "7", price: 2699 },
      { size: "8", price: 2799 },
      { size: "9", price: 2899 },
      { size: "10", price: 2999 },
    ],
  },
];
